---
grub:
    - grub
    - grub-customizer
    - os-prober
kernel:
    - linux
    - linux-firmware
    - linux-lts
    - linux-lts-headers
drivers:
    - hplip
    - xf86-video-nouveau
    - xf86-video-vesa
    - usb_modeswitch
    - mobile-broadband-provider-info
    - modemmanager
    - nm-connection-editor
lib:
    - libdvdread
    - libdvdcss
    - libdvdnav
    - python-configobj
display_manager:
    - lightdm
desktop_env:
    - cinnamon
    - nemo
    - nemo-fileroller
    - nemo-share
    - nemo-seahorse
themes:
    - mint-themes
    - mint-x-icons
desktop_utilities:
    - baobab
    - brasero
    - bluez
    - blueman
    - deja-dup
    - evince
    - gnome-calculator
    - gnome-disk-utility
    - gnome-screenshot
    - gnome-keyring
    - gparted
    - gsmartcontrol
    - libreoffice-fresh
    - simple-scan
accessories:
    - keepassxc
    - gedit
    - meld
    - mplayer
    - seahorse
    - vim
    - curl
clients:
    - firefox
    - filezilla
    - thunderbird
    - thunderbird-extension-enigmail
    - transmission-gtk
games:
    - pcsxr
file_system:
    - cifs-utils
    - libmtp
    - gvfs-smb
    - gvfs-mtp
    - mtpfs
    - nfs-utils
    - ntfs-3g
    - samba
graphics:
    - eog
    - gimp
    - pinta
bash:
    - bash-completion
    - neofetch
    - tree
dev:
    - code
sys:
    - bind-tools
    - dialog
    - docker
    - git
    - keychain
    - htop
    - lsof
    - linux-lts
    - mlocate
    - net-tools
    - netctl
    - openssh
    - pacman-contrib
    - rsync
    - smbclient
    - smartmontools
    - sslscan
    - tcpdump
    - terminator
    - usbutils
    - whois
video:
    - vlc
    - totem
    - openshot
astronomy:
    - celestia
    - stellarium
